### ISSUE TITLE
usage question

### ISSUE THREAD

**Issue by Cl0ckm4n** [pawanbahuguna/action-logs#5]
can i use this script only to add the logs to my repository by committing them or is it possible to download the logs to my local machine if a run Github-Actions on the machines provided by github?

**Comment by pawanbahuguna** [comment]
> can i use this script only to add the logs to my repository by committing them or is it possible to download the logs to my local machine if a run Github-Actions on the machines provided by github?

This action only needs your GH token with the correct permission, so it should work if you want to run it on your local machine. Just make sure you are using the proper image. Let me know how it goes.
